apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-basic-deployment
  labels:
    app: angular-basic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: angular-basic
      tier: web
  template:
    metadata:
      labels:
        app: angular-basic
        tier: web
    spec:
      containers:
      - name: angular-basic
        image: everecidocker/angular-basic:latest
        ports:
        - containerPort: 4200
          name: angular-basic