apiVersion: apps/v1
kind: Deployment
metadata:
  name: fe-testeatest-deployment
  labels:
    app: fe-testeatest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fe-testeatest
      tier: web
  template:
    metadata:
      labels:
        app: fe-testeatest
        tier: web
    spec:
      containers:
      - name: fe-testeatest
        image: everecidocker/fe-testeatest:latest
        ports:
        - containerPort: 4200
          name: fe-testeatest